import type { Meta, StoryObj } from "@storybook/react";
import Table from "./Table";

//👇 This default export determines where your story goes in the story list
const meta: Meta<typeof Table> = {
  component: Table,
};

export default meta;
type Story = StoryObj<typeof Table>;

export const TableStory: Story = {
  render: (args) => <Table {...args} />,
  args: {
    id: "table-1",
    stickyFirstColumn: true,
    header: [
      { label: "header1", id: "header1" },
      { label: "header2", id: "header2" },
      { label: "header3", id: "header3" },
      { label: "header4", id: "header4" },
      { label: "header5", id: "header5" },
      { label: "header6", id: "header6" },
      { label: "header7", id: "header7" },
      { label: "header8", id: "header8" },
      { label: "header9", id: "header9" },
      { label: "header10", id: "header10" },
      { label: "header11", id: "header11" },
      { label: "header12", id: "header12" },
      { label: "header13", id: "header13" },
      { label: "header14", id: "header14" },
      { label: "header15", id: "header15" },
      { label: "header16", id: "header16" },
      { label: "header17", id: "header17" },
      { label: "header18", id: "header18" },
      { label: "header19", id: "header19" },
      { label: "header20", id: "header20" },
    ],
    content: [
      {
        columns: [
          "col1 long lorem ipsum dolor sit amet",
          "col2",
          "col3",
          "col4",
          "col5",
          "col6",
          "col7",
          "col8",
          "col9",
          "col10",
          "col11",
          "col12",
          "col13",
          "col14",
          "col15",
          "col16",
          "col17",
          "col18",
          "col19",
          "col20",
        ],
      },
      {
        columns: [
          "col1",
          "col2",
          "col3",
          "col4",
          "col5",
          "col6",
          "col7",
          "col8",
          "col9",
          "col10",
          "col11",
          "col12",
          "col13",
          "col14",
          "col15",
          "col16",
          "col17",
          "col18",
          "col19",
          "col20",
        ],
      },
      {
        columns: [
          "col1",
          "col2",
          "col3",
          "col4",
          "col5",
          "col6",
          "col7",
          "col8",
          "col9",
          "col10",
          "col11",
          "col12",
          "col13",
          "col14",
          "col15",
          "col16",
          "col17",
          "col18",
          "col19",
          "col20",
        ],
      },
      {
        columns: [
          "col1",
          "col2",
          "col3",
          "col4",
          "col5",
          "col6",
          "col7",
          "col8",
          "col9",
          "col10",
          "col11",
          "col12",
          "col13",
          "col14",
          "col15",
          "col16",
          "col17",
          "col18",
          "col19",
          "col20",
        ],
      },
      {
        columns: [
          "col1",
          "col2",
          "col3",
          "col4",
          "col5",
          "col6",
          "col7",
          "col8",
          "col9",
          "col10",
          "col11",
          "col12",
          "col13",
          "col14",
          "col15",
          "col16",
          "col17",
          "col18",
          "col19",
          "col20",
        ],
      },
      {
        columns: [
          "col1",
          "col2",
          "col3",
          "col4",
          "col5",
          "col6",
          "col7",
          "col8",
          "col9",
          "col10",
          "col11",
          "col12",
          "col13",
          "col14",
          "col15",
          "col16",
          "col17",
          "col18",
          "col19",
          "col20",
        ],
      },
      {
        columns: [
          "col1",
          "col2",
          "col3",
          "col4",
          "col5",
          "col6",
          "col7",
          "col8",
          "col9",
          "col10",
          "col11",
          "col12",
          "col13",
          "col14",
          "col15",
          "col16",
          "col17",
          "col18",
          "col19",
          "col20",
        ],
      },
      {
        columns: [
          "col1",
          "col2",
          "col3",
          "col4",
          "col5",
          "col6",
          "col7",
          "col8",
          "col9",
          "col10",
          "col11",
          "col12",
          "col13",
          "col14",
          "col15",
          "col16",
          "col17",
          "col18",
          "col19",
          "col20",
        ],
      },
    ],
  },
};
